config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("geces.core.urls", namespace="")),
    path("users/", include("geces.users.urls", namespace="users")),
    path("canteen/", include("geces.canteen.urls", namespace="canteen")),
    path("finance/", include("geces.finance.urls", namespace="finance")),
    path("people/", include("geces.people.urls", namespace="people")),
    path("academics/", include("geces.academics.urls", namespace="academics")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("select2/", include("django_select2.urls")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geces/academics/urls.py
from django.urls import path

from . import views

app_name = "academics"
urlpatterns = [
    path("", views.AcademicsHome.as_view(), name="academics_home"),
    # Serie URLs
    path("series/", views.SerieListView.as_view(), name="serie_list"),
    path("serie_create/", views.SerieCreateView.as_view(), name="serie_create"),
    path("serie_update/<int:pk>/", views.SerieUpdateView.as_view(), name="serie_update"),
    path("serie_detail/<int:pk>/", views.SerieDetailView.as_view(), name="serie_detail"),
    path("serie_delete/<int:pk>/", views.SerieDeleteView.as_view(), name="serie_delete"),
    # Enrollment URLs
    path("enrollments/", views.EnrollmentListView.as_view(), name="enrollment_list"),
    path("enrollment_create/", views.EnrollmentCreateView.as_view(), name="enrollment_create"),
    path("enrollment_update/<int:pk>/", views.EnrollmentUpdateView.as_view(), name="enrollment_update"),
    path("enrollment_detail/<int:pk>/", views.EnrollmentDetailView.as_view(), name="enrollment_detail"),
    path("enrollment_delete/<int:pk>/", views.EnrollmentDeleteView.as_view(), name="enrollment_delete"),
    # Group URLs
    path("student_groups/", views.StudentGroupListView.as_view(), name="student_group_list"),
    path("student_group_create/", views.StudentGroupCreateView.as_view(), name="student_group_create"),
    path("student_group_update/<int:pk>/", views.StudentGroupUpdateView.as_view(), name="student_group_update"),
    path("student_group_detail/<int:pk>/", views.StudentGroupDetailView.as_view(), name="student_group_detail"),
    # path("student_group_delete/<int:pk>/", views.GroupDeleteView.as_view(), name="student_group_delete"),
    path("get_student_group_by_year/", views.get_student_group_by_year, name="get_student_group_by_year"),
]

geces/finance/urls.py
from django.urls import path

from geces.finance import views

app_name = "finance"
urlpatterns = [
    path("invoices/<int:pk>/", views.invoice_list_pdf, name="invoice_list"),
]

geces/academics/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from geces.core import constants
from geces.core.models import BaseModel
from geces.people.models import Student, Teacher


# Create your models here.
class Shift(BaseModel):
    code = models.CharField(
        verbose_name=_("Código"),
        max_length=constants.SMALL_CHAR_FIELD_NAME_LENGTH,
        unique=True,
    )
    name = models.CharField(verbose_name=_("Nome"), max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH, unique=True)

    class Meta:
        verbose_name = _("Turno")
        verbose_name_plural = _("Turnos")

    def __str__(self):
        return self.name


class Serie(BaseModel):
    code = models.CharField(
        verbose_name=_("Código"),
        max_length=constants.SMALL_CHAR_FIELD_NAME_LENGTH,
        unique=True,
    )
    name = models.CharField(verbose_name=_("Nome"), max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH)
    shift = models.ForeignKey(
        Shift,
        verbose_name=_("Turno"),
        on_delete=models.PROTECT,
        related_name="series",
    )
    teachers = models.ManyToManyField(
        Teacher,
        verbose_name=_("Docente"),
        related_name="series",
    )

    class Meta:
        verbose_name = _("Série")
        verbose_name_plural = _("Séries")

    def __str__(self):
        return f"{self.name} - {self.shift.name}"


class StudentGroup(BaseModel):
    code = models.CharField(
        verbose_name=_("Código"),
        max_length=constants.SMALL_CHAR_FIELD_NAME_LENGTH,
        unique=True,
    )
    reference_year = models.PositiveSmallIntegerField(verbose_name=_("Ano referência"))
    offers = models.PositiveSmallIntegerField(verbose_name=_("Limite de Discentes"))
    serie = models.ForeignKey(
        Serie,
        verbose_name=_("Série"),
        on_delete=models.PROTECT,
        related_name="student_groups",
    )
    students = models.ManyToManyField(
        Student,
        through="Enrollment",
        verbose_name=_("Discentes"),
        related_name="student_groups",
    )

    class Meta:
        verbose_name = _("Turma")
        verbose_name_plural = _("Turmas")

    def __str__(self):
        return f"{self.serie.name} - {self.serie.shift.name}"


# TODO: Verify active enrollments before new enrollment
class Enrollment(BaseModel):
    class Status(models.IntegerChoices):
        ACTIVE = 1, _("Ativa")
        CANCELED = 2, _("Cancelada")
        FINISHED = 3, _("Concluída")  # Discente concluiu a oferta de disciplina

    status = models.PositiveSmallIntegerField(
        verbose_name=_("Situação"),
        choices=Status.choices,
        validators=[MinValueValidator(1), MaxValueValidator(3)],
    )

    code = models.CharField(
        verbose_name=_("Código"),
        max_length=constants.SMALL_CHAR_FIELD_NAME_LENGTH,
        unique=True,
    )
    student = models.ForeignKey(
        Student,
        verbose_name=_("Discente"),
        related_name="enrollments",
        on_delete=models.CASCADE,
    )
    student_group = models.ForeignKey(
        StudentGroup,
        verbose_name=_("Turma"),
        related_name="enrollments",
        on_delete=models.CASCADE,
    )
    enrollment_date = models.DateField(
        verbose_name=_("Data de Matrícula"),
        auto_now_add=True,
    )

    class Meta:
        verbose_name = _("Matrícula")
        verbose_name_plural = _("Matrículas")

    def __str__(self):
        return f"{self.student.name} matriculado em {self.student_group.code}"

    def save(self, *args, **kwargs):
        if not self.code:
            super().save(*args, **kwargs)
            enrollment_date = self.created_at.date() if self.created_at else timezone.now().date()
            self.code = f"{enrollment_date.year}{self.student_group.serie.shift.code}{self.student_group.serie.code}{self.pk}"  # noqa
            self.student.status = Student.Status.ENROLLED
            self.student.save()
        super().save(*args, **kwargs)

geces/academics/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, ExpressionWrapper, F, IntegerField
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_filters.views import FilterView

from geces.academics.filters import StudentGroupFilterSet
from geces.core.mixins import ProtectedMessageMixin, TitleBaseViewMixin

from . import forms, models

# Create your views here.


class AcademicsHome(TitleBaseViewMixin, generic.TemplateView):
    template_name = "academics/academics.html"
    title = _("Acadêmico")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["series_count"] = models.Serie.objects.count()
        context["student_groups_count"] = models.StudentGroup.objects.count()
        context["enrollments_count"] = models.Enrollment.objects.count()
        return context


class SerieListView(LoginRequiredMixin, TitleBaseViewMixin, generic.ListView):
    model = models.Serie
    template_name = "series/series_list.html"
    paginate_by = 10
    title = _("Lista de Séries")


class SerieCreateView(LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.CreateView):
    model = models.Serie
    title = _("Cadastro de Matrícula")
    template_name = "series/serie_form.html"
    form_class = forms.SerieForm
    success_url = reverse_lazy("academics:serie_list")
    success_message = _("A série foi cadastrada com sucesso")


class SerieUpdateView(LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.UpdateView):
    model = models.Serie
    title = _("Atualização de Série")
    template_name = "series/serie_form.html"
    form_class = forms.SerieForm
    success_url = reverse_lazy("academics:serie_list")
    success_message = _("A série foi atualizada com sucesso")


class SerieDetailView(LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.DetailView):
    model = models.Serie
    title = _("Detalhes da Série")
    template_name = "series/serie_detail.html"


class SerieDeleteView(LoginRequiredMixin, messages.views.SuccessMessageMixin, generic.DeleteView):
    model = models.Serie
    success_url = reverse_lazy("academics:serie_list")
    success_message = _("A série foi excluída com sucesso")


class EnrollmentListView(LoginRequiredMixin, TitleBaseViewMixin, generic.ListView):
    model = models.Enrollment
    template_name = "enrollments/enrollment_list.html"
    paginate_by = 10
    title = _("Lista de Matrículas")


class EnrollmentDetailView(LoginRequiredMixin, TitleBaseViewMixin, generic.DetailView):
    model = models.Enrollment
    title = _("Detalhes da Matrícula")
    template_name = "enrollments/enrollment_detail.html"
    title = _("Detalhes da Matrícula")


class EnrollmentCreateView(
    LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.CreateView
):
    model = models.Enrollment
    title = _("Cadastro de Matrícula")
    template_name = "enrollments/enrollment_form.html"
    form_class = forms.EnrollmentForm
    success_url = reverse_lazy("academics:enrollment_list")
    success_message = _("A matrícula foi cadastrada com sucesso")


class EnrollmentUpdateView(
    LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.UpdateView
):
    model = models.Enrollment
    title = _("Atualização de Matrícula")
    template_name = "enrollments/enrollment_form.html"
    form_class = forms.EnrollmentForm
    success_url = reverse_lazy("academics:enrollment_list")
    success_message = _("A matrícula foi atualizada com sucesso.")


class EnrollmentDeleteView(
    LoginRequiredMixin, ProtectedMessageMixin, messages.views.SuccessMessageMixin, generic.DeleteView
):
    model = models.Enrollment
    success_url = reverse_lazy("academics:enrollment_list")
    success_message = _("A matrícula foi excluída com sucesso.")
    protected_message = _("Não é possível excluir uma matrícula com faturas associadas.")


class StudentGroupListView(LoginRequiredMixin, TitleBaseViewMixin, FilterView):
    model = models.StudentGroup
    filterset_class = StudentGroupFilterSet
    template_name = "student_group/student_group_list.html"
    paginate_by = 10
    title = _("Lista de Turmas")
    ordering = ["serie__name"]

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(
            num_students=Count("students"),
            percentage=ExpressionWrapper((F("num_students") * 100.0) / F("offers"), output_field=IntegerField()),
        )
        return queryset


# TODO: Select reference year to filter student groups


class StudentGroupCreateView(
    LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.CreateView
):
    model = models.StudentGroup
    title = _("Cadastro de Turma")
    template_name = "student_group/student_group_form.html"
    form_class = forms.StudentGroupForm
    success_url = reverse_lazy("academics:student_group_list")
    success_message = _("A turma foi cadastrada com sucesso")


class StudentGroupUpdateView(
    LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.UpdateView
):
    model = models.StudentGroup
    title = _("Atualização de Turma")
    template_name = "student_group/student_group_form.html"
    form_class = forms.StudentGroupForm
    success_url = reverse_lazy("academics:student_group_list")
    success_message = _("A turma foi atualizada com sucesso")


class StudentGroupDetailView(
    LoginRequiredMixin, TitleBaseViewMixin, messages.views.SuccessMessageMixin, generic.DetailView
):
    model = models.StudentGroup
    title = _("Detalhes da Turma")
    template_name = "student_group/student_group_detail.html"


def get_student_group_by_year(request):
    if request.method == "GET" and "reference_year" in request.GET:
        group = (
            models.StudentGroup.objects.filter(reference_year=request.GET.get("reference_year"))
            .values("id", "serie__name", "serie__shift__name")
            .distinct()
        )

        return JsonResponse({"student_groups": list(group)})
    return JsonResponse({"error": "Invalid request"})

geces/academics/templates/enrollments/enrollment_detail.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Academics" url="academics:academics_home" %}
  {% breadcrumb_item text="Lista de Matrículas" url="academics:enrollment_list" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Dados da Matrícula</h3>
    </div>
    <div class="card-body p-0">
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Discente:</strong>
        </div>
        <div id="codigo" class="col-md-10 col-sm-12">{{ object.student.name }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Código da Turma:</strong>
        </div>
        <div id="codigo" class="col-md-10 col-sm-12">{{ object.code }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Turma:</strong>
        </div>
        <div id="name" class="col-md-10 col-sm-12">{{ object.student_group }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Professor:</strong>
        </div>
        <div id="teacher" class="col-md-10 col-sm-12">{{ object.student_group.serie.teacher.name }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Data da Matrícula:</strong>
        </div>
        <div id="teacher" class="col-md-10 col-sm-12">{{ object.enrollment_date }}</div>
      </div>
      <div class="row justify-content-between m-3">
        <div class="col-lg-4 col-md-6 col-12 m-3">
          <a type="button"
             class="btn btn-secondary"
             href="{% url 'academics:enrollment_list' %}"> <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>Voltar</a>
        </div>
        <div class="col-lg-2 col-md-3 col-12 m-3">
          <a class="btn btn-primary"
             href="{% url 'academics:enrollment_update' object.pk %}">Editar</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

geces/academics/templates/enrollments/enrollment_form.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap5 %}
{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Acadêmico" url="academics:academics_home" %}
  {% breadcrumb_item text="Lista de Matrículas" url="academics:enrollment_list" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  {% block alerts %}
    {% include "layouts/alerts.html" %}
  {% endblock alerts %}
  <div class="card card-primary mx-3">
    <div class="card-header">
      <h3 class="card-title">Matrícula</h3>
    </div>
    <div class="card-body p-0 mt-3">
      <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="row mx-auto mb-3">
          <div class="col-12 col-sm-6">{% bootstrap_field form.reference_year %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.student_group %}</div>
        </div>
        <div class="row mx-auto mb-3">
          <div class="col-12 col-sm-6">{% bootstrap_field form.student %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.status %}</div>
        </div>
        {% url "academics:enrollment_list" as enrollment_list %}
        {% save_cancel_buttons link_back=enrollment_list has_form=True %}
      </form>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  {{ form.media }}
  <script>
    $(document).ready(function() {
      $('#id_reference_year').on('change', function() {
        var reference_year = $(this).val();

        $.ajax({
          url: "{% url 'academics:get_student_group_by_year' %}",
          method: 'GET',
          data: {
            'reference_year': reference_year
          },
          dataType: 'json',
          success: function(data) {
            var studentGroupSelect = $('#id_student_group');
            studentGroupSelect.empty();
            console.log(data.student_groups);

            if (data.student_groups) {
              $.each(data.student_groups, function(index, group) {
                studentGroupSelect.append($('<option>', {
                  value: group.id,
                  text: group.serie__name + ' - ' + group.serie__shift__name
                }));
              });
              studentGroupSelect.prop('disabled', false); // Habilita o campo de seleção da turma
            } else {
              studentGroupSelect.prop('disabled', true); // Desativa o campo de seleção da turma se não houver séries
            }
          },
          error: function(err) {
            console.log('Erro ao buscar as séries:', err);
          }
        });
      });
    });
  </script>
{% endblock extra_js %}

geces/academics/templates/enrollments/enrollment_list.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap5 %}
{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Acadêmico" url="academics:academics_home" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Matrículas Cadastradas</h3>
    </div>
    <div class="card-body p-0" style="overflow-x: auto">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Código</th>
            <th>Discente</th>
            <th>Turma</th>
            <th>Ano</th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.code }}</td>
              <td>{{ object.student }}</td>
              <td>{{ object.student_group }}</td>
              <td>{{ object.student_group.reference_year }}</td>
              <td class="text-center">
                <a title="carnê" href="{% url 'finance:invoice_list' object.pk %}"><i class="fas fa-download" aria-hidden="true"></i></a>
                <a title="visualizar"
                   href="{% url 'academics:enrollment_detail' object.pk %}"><i class="fas fa-eye" aria-hidden="true"></i></a>
                <a title="editar"
                   class="mx-1"
                   href="{% url 'academics:enrollment_update' object.pk %}"
                   type="button"
                   aria-label="editar"
                   title="editar">
                  <i class="fas fa-edit" aria-hidden="true"></i></a>
                <a title="excluir"
                   type="button"
                   data-bs-toggle="modal"
                   data-bs-target="#deleteModal-{{ object.pk }}"
                   aria-label="excluir"
                   title="excluir">
                  <i class="fas fa-trash" aria-hidden="true"></i></a>
                {% include "academics/academics_confirm_delete.html" with delete_url="academics:enrollment_delete" %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">
                <p>Não existem séries cadastradas.</p>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if object_list %}
      {% include 'adminlte/lib/_pagination.html' %}
    {% endif %}
  </div>
  {% url "academics:academics_home" as academics_home %}
  {% url "academics:enrollment_create" as enrollment_create %}
  {% save_cancel_buttons link_back=academics_home link_forward=enrollment_create %}
{% endblock content %}