config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("geces.core.urls", namespace="")),
    path("users/", include("geces.users.urls", namespace="users")),
    path("canteen/", include("geces.canteen.urls", namespace="canteen")),
    path("finance/", include("geces.finance.urls", namespace="finance")),
    path("people/", include("geces.people.urls", namespace="people")),
    path("academics/", include("geces.academics.urls", namespace="academics")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("select2/", include("django_select2.urls")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geces/people/urls.py
from django.urls import path

from . import views

app_name = "people"
urlpatterns = [
    path("", views.PeopleHome.as_view(), name="people_home"),
    # Responsible URLs
    path("responsible_list/", views.ResponsbileList.as_view(), name="responsible_list"),
    path("responsible_form/", views.ResponsibleForm.as_view(), name="responsible_form"),
    path("responsible_edit/<int:pk>/", views.ResponsibleUpdate.as_view(), name="responsible_edit"),
    path("responsible_detail/<int:pk>/", views.ResponsbileDetail.as_view(), name="responsible_detail"),
    path("responsible_delete/<int:pk>/", views.ResponsbileDelete.as_view(), name="responsible_delete"),
    # Teacher URLs
    path("teacher_list/", views.TeacherList.as_view(), name="teacher_list"),
    path("teacher_form/", views.TeacherForm.as_view(), name="teacher_form"),
    path("teacher_detail/<int:pk>/", views.TeacherDetail.as_view(), name="teacher_detail"),
    path("teacher_edit/<int:pk>/", views.TeacherUpdate.as_view(), name="teacher_edit"),
    path("teacher_delete/<int:pk>/", views.TeacherDelete.as_view(), name="teacher_delete"),
    # Student URLs
    path("student_list/", views.StudentList.as_view(), name="student_list"),
    path("student_form/", views.StudentForm.as_view(), name="student_form"),
    path("student_detail/<int:pk>/", views.StudentDetail.as_view(), name="student_detail"),
    path("student_edit/<int:pk>/", views.StudentUpdate.as_view(), name="student_edit"),
    path("student_delete/<int:pk>/", views.StudentDelete.as_view(), name="student_delete"),
]

geces/people/models.py
import re

from cpf_field.models import CPFField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from geces.core import constants
from geces.core.models import BaseModel


class Address(BaseModel):
    city = models.CharField(verbose_name=_("Cidade"), max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH)
    address = models.CharField(verbose_name=_("Endereço"), max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH)
    zip_code = models.CharField(verbose_name=_("CEP"), max_length=10)
    phone = models.CharField(verbose_name=_("Telefone"), max_length=constants.MEDIUM_CHAR_FIELD_NAME_LENGTH)

    class Meta:
        verbose_name = _("Endereço")
        verbose_name_plural = _("Endereços")

    def __str__(self):
        full_address = _("{address}, {city}, CEP {zip_code}")
        return full_address.format(
            address=self.address,
            city=self.city,
            zip_code=self.zip_code,
        )


class PersonBase(BaseModel):
    class Gender(models.TextChoices):
        MALE = "MALE", _("Masculino")
        FEMALE = "FEMALE", _("Feminino")

    name = models.CharField(
        verbose_name=_("Nome"),
        max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH,
    )
    email = models.EmailField(
        verbose_name=_("E-mail"),
        max_length=constants.MEDIUM_CHAR_FIELD_NAME_LENGTH,
        unique=True,
    )
    cpf = CPFField(_("CPF"), unique=False)
    gender = models.CharField(
        verbose_name=_("Gênero"),
        max_length=constants.SMALL_CHAR_FIELD_NAME_LENGTH,
        choices=Gender.choices,
    )
    birth = models.DateField(verbose_name=_("Nascimento"))
    address = models.ForeignKey(
        Address,
        verbose_name=_("Endereço"),
        on_delete=models.PROTECT,
        related_name="%(class)s",
    )

    class Meta:
        abstract = True
        verbose_name = _("Pessoa")
        verbose_name_plural = _("Pessoas")

    def __str__(self):
        return self.name

    def get_clean_cpf(self):
        return re.sub("[^0-9]", "", self.cpf)


class Suplier(PersonBase):
    class Meta:
        verbose_name = _("Fornecedor")
        verbose_name_plural = _("Fornecedores")

    def __str__(self):
        return str(self.name)


class Teacher(PersonBase):
    class Meta:
        verbose_name = _("Professor")
        verbose_name_plural = _("Professores")

    def __str__(self):
        return str(self.name)


class Responsible(PersonBase):
    class Meta:
        verbose_name = _("Responsável")
        verbose_name_plural = _("Responsáveis")

    def __str__(self):
        return str(self.name)


class Student(PersonBase):
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pendente")
        ENROLLED = 2, _("Matriculado")
        STUDYING = 3, _("Cursando")

    status = models.PositiveSmallIntegerField(
        verbose_name=_("Situação"),
        choices=Status.choices,
        validators=[MinValueValidator(1), MaxValueValidator(3)],
        default=Status.PENDING,
    )
    responsible = models.ForeignKey(
        Responsible,
        verbose_name=_("Responsável"),
        on_delete=models.PROTECT,
        null=True,
        related_name="students",
    )
    balance = models.DecimalField(_("Saldo"), max_digits=5, decimal_places=2, default=0.00)

    @property
    def active_enrollment(self):
        return self.enrollments.filter(status=1).first()

    class Meta:
        verbose_name = _("Discente")
        verbose_name_plural = _("Discentes")

    def __str__(self):
        return str(self.name)

geces/people/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from geces.core.mixins import TitleBaseViewMixin
from geces.people import forms, models
from geces.people.mixins import PeopleCreateViewMixin


# Create your views here.
class PeopleHome(LoginRequiredMixin, TitleBaseViewMixin, generic.TemplateView):
    template_name = "people/people.html"
    title = _("Pessoas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["teacher_count"] = models.Teacher.objects.count()
        context["student_count"] = models.Student.objects.count()
        context["responsible_count"] = models.Responsible.objects.count()
        return context


class StudentList(LoginRequiredMixin, TitleBaseViewMixin, generic.ListView):
    model = models.Student
    title = _("Lista de Discentes")
    template_name = "student/student_list.html"
    paginate_by = 10
    ordering = ["name"]


class StudentForm(
    LoginRequiredMixin,
    TitleBaseViewMixin,
    messages.views.SuccessMessageMixin,
    PeopleCreateViewMixin,
    generic.CreateView,
):
    model = models.Student
    title = _("Cadastro de Discente")
    template_name = "student/student_form.html"
    form_class = forms.StudentForm
    success_message = _("O discente foi cadastrado com sucesso")
    success_url = reverse_lazy("people:student_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.created_by = self.request.user
        form.instance.created_by = self.request.user
        if address_form.is_valid():
            responsible_name = form.cleaned_data["responsible"]
            responsible = models.Responsible.objects.filter(name=responsible_name).first()
            student = form.save(commit=False)
            student.responsible = responsible
            address = address_form.save()
            student.address = address
            student.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class StudentDetail(LoginRequiredMixin, TitleBaseViewMixin, generic.DetailView):
    model = models.Student
    title = _("Detalhes do Discente")
    slug_field = "id"
    slug_url_kwarg = "id"
    template_name = "student/student_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["student_group"] = self.get_object().student_groups.all()
        return context


class StudentUpdate(
    LoginRequiredMixin,
    TitleBaseViewMixin,
    messages.views.SuccessMessageMixin,
    PeopleCreateViewMixin,
    generic.UpdateView,
):
    model = models.Student
    title = _("Atualização de Discente")
    template_name = "student/student_form.html"
    form_class = forms.StudentForm
    success_message = _("O discente foi atualizado com sucesso")
    success_url = reverse_lazy("people:student_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.updated_by = self.request.user
        form.instance.updated_by = self.request.user
        if address_form.is_valid():
            student = form.save(commit=False)
            address = address_form.save()
            student.address = address
            student.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class StudentDelete(LoginRequiredMixin, generic.DeleteView):
    model = models.Student
    success_url = reverse_lazy("people:student_list")
    success_message = _("Discente excluído com sucesso!")


class ResponsbileList(LoginRequiredMixin, TitleBaseViewMixin, generic.ListView):
    model = models.Responsible
    template_name = "responsible/responsible_list.html"
    paginate_by = 10
    ordering = ["name"]
    title = _("Lista de Responsáveis")


class ResponsbileDelete(LoginRequiredMixin, generic.DeleteView):
    model = models.Responsible
    success_url = reverse_lazy("people:responsible_list")
    success_message = _("Responsável excluído com sucesso!")


class ResponsbileDetail(LoginRequiredMixin, TitleBaseViewMixin, generic.DetailView):
    model = models.Responsible
    slug_field = "id"
    slug_url_kwarg = "id"
    template_name = "responsible/responsible_detail.html"
    title = _("Detalhes do Responsável")


class ResponsibleForm(
    LoginRequiredMixin,
    messages.views.SuccessMessageMixin,
    TitleBaseViewMixin,
    PeopleCreateViewMixin,
    generic.CreateView,
):
    model = models.Responsible
    title = _("Cadastro de Responsável")
    template_name = "responsible/responsible_form.html"
    form_class = forms.ResponsibleForm
    success_message = _("O responsável foi cadastrado com sucesso")
    success_url = reverse_lazy("people:responsible_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.created_by = self.request.user
        form.instance.created_by = self.request.user
        if address_form.is_valid():
            responsible = form.save(commit=False)
            address = address_form.save()
            responsible.address = address
            responsible.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ResponsibleUpdate(
    LoginRequiredMixin,
    TitleBaseViewMixin,
    messages.views.SuccessMessageMixin,
    PeopleCreateViewMixin,
    generic.UpdateView,
):
    model = models.Responsible
    title = _("Atualização de Responsável")
    template_name = "responsible/responsible_form.html"
    form_class = forms.ResponsibleForm
    success_message = _("O responsável foi atualizado com sucesso")
    success_url = reverse_lazy("people:responsible_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.updated_by = self.request.user
        form.instance.updated_by = self.request.user
        if address_form.is_valid():
            responsible = form.save(commit=False)
            address = address_form.save()
            responsible.address = address
            responsible.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class TeacherList(LoginRequiredMixin, TitleBaseViewMixin, generic.ListView):
    model = models.Teacher
    title = _("Lista de Professores")
    template_name = "teacher/teacher_list.html"
    paginate_by = 10
    ordering = ["name"]


class TeacherForm(
    LoginRequiredMixin,
    TitleBaseViewMixin,
    messages.views.SuccessMessageMixin,
    PeopleCreateViewMixin,
    generic.CreateView,
):
    model = models.Teacher
    title = _("Cadastro de Professor")
    template_name = "teacher/teacher_form.html"
    form_class = forms.TeacherForm
    success_message = _("O professor foi cadastrado com sucesso")
    success_url = reverse_lazy("people:teacher_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.created_by = self.request.user
        form.instance.created_by = self.request.user
        if address_form.is_valid():
            teacher = form.save(commit=False)
            address = address_form.save()
            teacher.address = address
            teacher.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class TeacherDetail(LoginRequiredMixin, TitleBaseViewMixin, generic.DetailView):
    model = models.Teacher
    title = _("Detalhes do Professor")
    slug_field = "id"
    slug_url_kwarg = "id"
    template_name = "teacher/teacher_detail.html"


class TeacherUpdate(
    LoginRequiredMixin,
    TitleBaseViewMixin,
    messages.views.SuccessMessageMixin,
    PeopleCreateViewMixin,
    generic.UpdateView,
):
    model = models.Teacher
    title = _("Atualização de Professor")
    template_name = "teacher/teacher_form.html"
    form_class = forms.TeacherForm
    success_message = _("O professor foi atualizado com sucesso.")
    success_url = reverse_lazy("people:teacher_list")

    @transaction.atomic
    def form_valid(self, form):
        address_form = forms.AddressForm(self.request.POST)
        address_form.updated_by = self.request.user
        form.instance.updated_by = self.request.user
        if address_form.is_valid():
            teacher = form.save(commit=False)
            address = address_form.save()
            teacher.address = address
            teacher.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class TeacherDelete(LoginRequiredMixin, generic.DeleteView):
    model = models.Teacher
    success_url = reverse_lazy("people:teacher_list")
    success_message = _("Professor excluído com sucesso!")

geces/people/templates/student/student_detail.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Pessoas" url="people:people_home" %}
  {% breadcrumb_item text="Lista de Discentes" url="people:teacher_list" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Dados do Discente</h3>
    </div>
    <div class="card-body p-0">
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Nome:</strong>
        </div>
        <div id="nome-completo" class="col-md-10 col-sm-12">{{ object.name }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Situação:</strong>
        </div>
        <div id="nome-completo" class="col-md-10 col-sm-12">{{ object.get_status_display }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Turma:</strong>
        </div>
        {% for group in student_group %}
          <div id="group" class="col-md-10 col-sm-12">
            {{ group.serie.name }} - {{ group.serie.shift.name }} - {{ group.reference_year }}
          </div>
        {% endfor %}
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Email:</strong>
        </div>
        <div id="email" class="col-md-10 col-sm-12">{{ object.email }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Gênero:</strong>
        </div>
        <div id="email" class="col-md-10 col-sm-12">{{ object.get_gender_display }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Endereço:</strong>
        </div>
        <div id="address" class="col-md-10 col-sm-12">{{ object.address.address }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Cidade:</strong>
        </div>
        <div id="city" class="col-md-10 col-sm-12">{{ object.address.city }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>CEP:</strong>
        </div>
        <div id="address" class="col-md-10 col-sm-12">{{ object.address.zip_code }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Telefone:</strong>
        </div>
        <div id="address" class="col-md-10 col-sm-12">{{ object.address.phone }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Responsável:</strong>
        </div>
        <div id="address" class="col-md-10 col-sm-12">
          <a href="{% url 'people:responsible_detail' object.responsible.pk %}">{{ object.responsible.name }}</a>
        </div>
      </div>
      <div class="row justify-content-between m-3">
        <div class="col-lg-4 col-md-6 col-12 m-3">
          <a type="button"
             class="btn btn-secondary"
             href="{{ request.META.HTTP_REFERER }}"> <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>Voltar</a>
        </div>
        <div class="col-lg-2 col-md-3 col-12 m-3">
          <a class="btn btn-primary"
             href="{% url 'people:student_edit' object.pk %}">Editar</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

geces/people/templates/student/student_form.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap5 %}
{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Pessoas" url="people:people_home" %}
  {% breadcrumb_item text="Lista de Discentes" url="people:student_list" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  {% block alerts %}
    {% include "layouts/alerts.html" %}
  {% endblock alerts %}
  <div class="card card-primary mx-3">
    <div class="card-header">
      <h3 class="card-title">Cadastro de Discente</h3>
    </div>
    <div class="card-body p-0 mt-3">
      <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="row mx-auto mb-3">
          <div class="col-12 col-sm-6">{% bootstrap_field form.cpf %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.name %}</div>
        </div>
        <div class="row mx-auto mb-3">
          <div class="col-12 col-sm-6">{% bootstrap_field form.email %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.birth %}</div>
        </div>
        <div class="row mx-auto mb-3">
          <div class="col-12 col-sm-6">{% bootstrap_field form.gender %}</div>
          <div class="col-12 col-sm-6">{% bootstrap_field form.responsible %}</div>
        </div>
        {% include "people/_address_form.html" %}
        <div class="row mx-auto mb-3"></div>
        {% url "people:student_list" as student_list %}
        {% save_cancel_buttons link_back=student_list has_form=True %}
      </form>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  {{ form.media }}
{% endblock extra_js %}

geces/people/templates/student/student_list.html
{% extends "base.html" %}

{% load i18n %}
{% load bootstrap5 %}
{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block page_name %}
  {{ title }}
{% endblock page_name %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Pessoas" url="people:people_home" %}
  {% breadcrumb_item text=title active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Lista de Discentes Cadastrados</h3>
    </div>
    <div class="card-body p-0" style="overflow-x: auto">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Turma</th>
            <th class="text-center">Situação</th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.name }}</td>
              <td>{{ object.email }}</td>
              <td>{{ object.address.phone }}</td>
              <td>
                {% if object.active_enrollment %}
                  {{ object.active_enrollment.student_group }}
                {% else %}
                  <span class="text-danger">Sem turma</span>
                {% endif %}
              </td>
              <td class="text-center">{{ object.get_status_display }}</td>
              <td class="text-center">
                <a href="{% url 'people:student_detail' object.pk %}"><i class="fas fa-eye" aria-hidden="true"></i></a>
                <a class="mx-1"
                   href="{% url 'people:student_edit' object.pk %}"
                   type="button"
                   aria-label="editar"
                   title="editar">
                  <i class="fas fa-edit" aria-hidden="true"></i></a>
                <a type="button"
                   data-bs-toggle="modal"
                   data-bs-target="#deleteModal-{{ object.pk }}"
                   aria-label="excluir"
                   title="excluir">
                  <i class="fas fa-trash" aria-hidden="true"></i></a>
                {% include "people/people_confirm_delete.html" with delete_url="people:student_delete" %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">
                <p>Não existem alunos cadastrados.</p>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% if object_list %}
      {% include 'adminlte/lib/_pagination.html' %}
    {% endif %}
  </div>
  {% url "people:people_home" as people_home %}
  {% url "people:student_form" as student_form %}
  {% save_cancel_buttons link_back=people_home link_forward=student_form %}
{% endblock content %}