config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("geces.core.urls", namespace="")),
    path("users/", include("geces.users.urls", namespace="users")),
    path("canteen/", include("geces.canteen.urls", namespace="canteen")),
    path("finance/", include("geces.finance.urls", namespace="finance")),
    path("people/", include("geces.people.urls", namespace="people")),
    path("academics/", include("geces.academics.urls", namespace="academics")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("select2/", include("django_select2.urls")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geces/movement/urls.py
from django.urls import path

from . import views

app_name = "movement"
urlpatterns = [
    path("cadastrar_produto/", views.ProductFormView.as_view(), name="product_form"),
    path("listar_produtos/", views.ProductListView.as_view(), name="products_list"),
    path("editar_produto/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("excluir_produto/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("visualizar_produto/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
]

geces/users/urls.py
from django.urls import path

from geces.users.views import (
    ThirdUserUpdateView,
    UserCreateView,
    UserDeleteView,
    UserDetailView,
    UsersListView,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="self-update"),
    path("detail/<int:pk>/", view=UserDetailView.as_view(), name="detail"),
    path("list/", view=UsersListView.as_view(), name="list"),
    path("signup/", view=UserCreateView.as_view(), name="signup"),
    path("edit/<int:pk>/", view=ThirdUserUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/", view=UserDeleteView.as_view(), name="delete"),
]

geces/canteen/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from geces.core import constants
from geces.core.models import BaseModel
from geces.people.models import Student, Suplier


class Product(BaseModel):
    name = models.CharField(_("Nome"), max_length=constants.MAX_CHAR_FIELD_NAME_LENGTH)
    price = models.DecimalField(_("Preço"), max_digits=5, decimal_places=2)
    stock = models.IntegerField(_("Estoque"), default=0)
    image = models.ImageField(
        upload_to="ProductImages",
        height_field=None,
        width_field=None,
        max_length=constants.MEDIUM_CHAR_FIELD_NAME_LENGTH,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _("Produto")
        verbose_name_plural = _("Produtos")

    def __str__(self):
        return self.name


class Purchase(BaseModel):
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pendente")
        PAID = 2, _("Pago")
        CANCELED = 3, _("Cancelado")

    supplier = models.ForeignKey(
        Suplier,
        verbose_name=_("Fornecedor"),
        on_delete=models.PROTECT,
        related_name="compras",
        null=True,
    )
    products = models.ManyToManyField(
        Product,
        verbose_name=_("Produtos"),
        related_name="compras",
        blank=True,
        through="ProductPurchase",
    )
    status = models.PositiveSmallIntegerField(
        verbose_name=_("Status"),
        choices=Status.choices,
        validators=[MinValueValidator(1), MaxValueValidator(3)],
    )

    class Meta:
        verbose_name = _("Compra")
        verbose_name_plural = _("Compras")

    def __str__(self):
        return str(self.created_at, self.supplier)


class ProductPurchase(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name=_("Produto"),
        on_delete=models.PROTECT,
        related_name="product_purchases",
    )
    purchase = models.ForeignKey(
        Purchase,
        verbose_name=_("Compra"),
        on_delete=models.PROTECT,
        related_name="product_purchases",
    )
    quantity = models.IntegerField(_("Quantidade"), default=0)

    class Meta:
        verbose_name = _("Produto Compra")
        verbose_name_plural = _("Produtos Compras")

    def __str__(self):
        return str(self.product, self.purchase, self.quantity)


class Sell(BaseModel):
    class Status(models.IntegerChoices):
        PENDING = 1, _("Pendente")
        PAID = 2, _("Pago")
        CANCELED = 3, _("Cancelado")

    student = models.ForeignKey(
        Student,
        verbose_name=_("Estudante"),
        on_delete=models.PROTECT,
        related_name="sells",
        null=True,
    )
    products = models.ManyToManyField(
        Product,
        verbose_name=_("Produtos"),
        related_name="sells",
        blank=True,
        through="ProductSell",
    )
    status = models.PositiveSmallIntegerField(
        verbose_name=_("Status"),
        choices=Status.choices,
        validators=[MinValueValidator(1), MaxValueValidator(3)],
    )

    class Meta:
        verbose_name = _("Venda")
        verbose_name_plural = _("Vendas")

    def __str__(self):
        return str(self.created_at, self.student)


class ProductSell(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name=_("Produto"),
        on_delete=models.PROTECT,
        related_name="product_sell",
    )
    sell = models.ForeignKey(
        Sell,
        verbose_name=_("Venda"),
        on_delete=models.PROTECT,
        related_name="product_sell",
    )
    quantity = models.IntegerField(_("Quantidade"), default=0)

    class Meta:
        verbose_name = _("Produto Venda")
        verbose_name_plural = _("Produtos Vendas")

    def __str__(self):
        return str(self.product, self.sell, self.quantity)

geces/movement/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from .forms import ProductForm
from .models import Product


class ProductFormView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    template_name = "products/products_form.html"
    success_url = reverse_lazy("movement:products_list")
    success_message = _("Produto cadastrado com sucesso!")


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "products/products_form.html"
    success_url = reverse_lazy("movement:products_list")
    success_message = _("Produto atualizado com sucesso!")


class ProductDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Product
    template_name = "products/products_confirm_delete.html"
    success_url = reverse_lazy("movement:products_list")
    success_message = _("Produto excluído com sucesso!")


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    paginate_by = 5
    ordering = ["name"]
    template_name = "products/products_list.html"
    queryset = Product.objects.all()


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    model = Product
    template_name = "products/product_detail.html"
    queryset = Product.objects.all()

geces/movement/templates/products/product_confirm_delete.html
<form action="{% url 'movement:product_delete' object.pk %}" method="post">
  {% csrf_token %}
  <div class="modal fade"
       id="deleteModal-{{ object.pk }}"
       tabindex="-1"
       aria-labelledby="deleteModalLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="deleteModalLabel">Confirmação de Exclusão</h1>
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"></button>
        </div>
        <div class="modal-body">Deseja excluir o produto {{ object.name }}?</div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-danger">Excluir</button>
        </div>
      </div>
    </div>
  </div>
</form>

geces/movement/templates/products/product_detail.html
{% extends "base.html" %}

{% load static %}
{% load breadcrumb_item %}

{% block title %}
  User:
  {{ object.name }}
{% endblock title %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Lista de Produtos" url="movement:products_list" %}
  {% breadcrumb_item text="Visualizar Produto" active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary m-3">
    <div class="card-header">
      <h3 class="card-title">Dados da usuário</h3>
    </div>
    <div class="card-body p-0">
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Nome:</strong>
        </div>
        <div id="nome-completo" class="col-md-10 col-sm-12">{{ object.name }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Preço:</strong>
        </div>
        <div id="email" class="col-md-10 col-sm-12">R$ {{ object.price }}</div>
      </div>
      <div class="row align-items-center m-3">
        <div class="col-md-2 col-sm-12">
          <strong>Estoque:</strong>
        </div>
        <div id="grupo" class="col-md-10 col-sm-12">{{ object.stock }}</div>
      </div>
      <div class="row align-items-center m-3">
        <p>TESTE</p>
      </div>
      <div class="row justify-content-between m-3">
        <div class="col-lg-4 col-md-6 col-12 m-3">
          <a type="button" class="btn btn-secondary" href="{% url 'users:list' %}"> <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>Voltar</a>
        </div>
        <div class="col-lg-2 col-md-3 col-12 m-3">
          <a class="btn btn-primary" href="{% url 'users:edit' object.pk %}">Editar</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

geces/movement/templates/products/products_form.html
{% extends "base.html" %}

{% load bootstrap5 %}
{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block title %}
  Cadastro de Produtos
{% endblock title %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Lista de Produtos" url="movement:products_list" %}
  {% breadcrumb_item text="Lista de Produtos" active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary mx-3">
    <div class="card-header">
      <div class="card-title">Cadastro de Produtos</div>
    </div>
    <div class="card-body">
      <form method="post" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% url "movement:products_list" as product_list %}
        {% save_cancel_buttons link_back=product_list has_form=True %}
      </form>
    </div>
  </div>
{% endblock content %}
{% block extra_js %}
  <script>
    $(document).ready(function() {
      $('.money').mask('000,00', {
        reverse: true
      });
    })
  </script>
{% endblock extra_js %}

geces/movement/templates/products/products_list.html
{% extends "base.html" %}

{% load save_cancel_buttons %}
{% load breadcrumb_item %}

{% block title %}
  Lista de Produtos
{% endblock title %}
{% block breadcrumb_items %}
  {{ block.super }}
  {% breadcrumb_item text="Página Inicial" url="home" %}
  {% breadcrumb_item text="Lista de Produtos" active="active" %}
{% endblock breadcrumb_items %}
{% block content %}
  <div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Lista de Produtos</h3>
    </div>
    <div class="card-body p-0">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Nome</th>
            <th class="text-center">Preço</th>
            <th class="text-center">Estoque</th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
            <tr>
              <td>{{ object.name }}</td>
              <td class="text-center">R$ {{ object.price }}</td>
              <td class="text-center">{{ object.stock }}</td>
              <td class="text-center">
                <a href="{% url 'movement:product_detail' object.pk %}"><i class="fas fa-eye" aria-hidden="true"></i></a>
                <a href="{% url 'movement:product_update' object.pk %}"
                   type="button"
                   aria-label="editar"
                   title="editar">
                  <i class="fas fa-edit" aria-hidden="true"></i></a>
                <a type="button"
                   data-bs-toggle="modal"
                   data-bs-target="#deleteModal-{{ object.pk }}"
                   aria-label="excluir"
                   title="excluir">
                  <i class="fas fa-trash" aria-hidden="true"></i></a>
                {% include "products/product_confirm_delete.html" %}
              </td>
              <td></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% url "home" as home_url %}
  {% url "movement:product_form" as product_form %}
  {% save_cancel_buttons link_back=home_url link_forward=product_form %}
{% endblock content %}